--To be expanded as masteries are added
return T{
	['WAR'] = {
		[1] = {Type='Auto-attack damage', Goal='5000', Bonus='10% more auto-attack damage'},
		[2] = {Type=false, Goal=false, Bonus=false},
		[3] = {Type=false, Goal=false, Bonus=false},
		[4] = {Type=false, Goal=false, Bonus=false},
		[5] = {Type=false, Goal=false, Bonus=false},
	},
	['MNK'] = {
		[1] = {Type='Auto-attack damage', Goal='5000', Bonus='10% more auto-attack damage'},
		[2] = {Type=false, Goal=false, Bonus=false},
		[3] = {Type=false, Goal=false, Bonus=false},
		[4] = {Type=false, Goal=false, Bonus=false},
		[5] = {Type=false, Goal=false, Bonus=false},
	},
	['WHM'] = {
		[1] = {Type='Healing done', Goal='5000', Bonus='10% cure potency'},
		[2] = {Type=false, Goal=false, Bonus=false},
		[3] = {Type=false, Goal=false, Bonus=false},
		[4] = {Type=false, Goal=false, Bonus=false},
		[5] = {Type=false, Goal=false, Bonus=false},
	},
	['BLM'] = {
		[1] = {Type='Damage with elemental spells', Goal='5000', Bonus='10% more elemental damage spell accuracy'},
		[2] = {Type=false, Goal=false, Bonus=false},
		[3] = {Type=false, Goal=false, Bonus=false},
		[4] = {Type=false, Goal=false, Bonus=false},
		[5] = {Type=false, Goal=false, Bonus=false},
	},
	['RDM'] = {
		[1] = {Type='Enfeebling spells cast', Goal='100', Bonus='10% more enfeebling spell accuracy'},
		[2] = {Type=false, Goal=false, Bonus=false},
		[3] = {Type=false, Goal=false, Bonus=false},
		[4] = {Type=false, Goal=false, Bonus=false},
		[5] = {Type=false, Goal=false, Bonus=false},
	},
	['THF'] = {
		[1] = {Type='Auto-attack damage', Goal='5000', Bonus='10% more auto-attack damage'},
		[2] = {Type='Sneak attacks', Goal='200', Bonus='Extra charge on sneak attack'},
		[3] = {Type=false, Goal=false, Bonus=false},
		[4] = {Type=false, Goal=false, Bonus=false},
		[5] = {Type=false, Goal=false, Bonus=false},
	},
	['PLD'] = {
		[1] = {Type='Damage blocked', Goal='5000', Bonus='10% increased shield block rate'},
		[2] = {Type=false, Goal=false, Bonus=false},
		[3] = {Type=false, Goal=false, Bonus=false},
		[4] = {Type=false, Goal=false, Bonus=false},
		[5] = {Type=false, Goal=false, Bonus=false},
	},
	['DRK'] = {
		[1] = {Type='Auto-attack damage', Goal='5000', Bonus='10% more auto-attack damage'},
		[2] = {Type=false, Goal=false, Bonus=false},
		[3] = {Type=false, Goal=false, Bonus=false},
		[4] = {Type=false, Goal=false, Bonus=false},
		[5] = {Type=false, Goal=false, Bonus=false},
	},
	['BST'] = {
		[1] = {Type='Charms or Jug Pets', Goal='100', Bonus='Pet auto-regen'},
		[2] = {Type=false, Goal=false, Bonus=false},
		[3] = {Type=false, Goal=false, Bonus=false},
		[4] = {Type=false, Goal=false, Bonus=false},
		[5] = {Type=false, Goal=false, Bonus=false},
	},
	['BRD'] = {
		[1] = {Type='Songs played', Goal='100', Bonus='10% longer song duration'},
		[2] = {Type=false, Goal=false, Bonus=false},
		[3] = {Type=false, Goal=false, Bonus=false},
		[4] = {Type=false, Goal=false, Bonus=false},
		[5] = {Type=false, Goal=false, Bonus=false},
	},
	['RNG'] = {
		[1] = {Type='Ranged attack damage', Goal='5000', Bonus='10% more ranged attack damage'},
		[2] = {Type=false, Goal=false, Bonus=false},
		[3] = {Type=false, Goal=false, Bonus=false},
		[4] = {Type=false, Goal=false, Bonus=false},
		[5] = {Type=false, Goal=false, Bonus=false},
	},
	['SAM'] = {
		[1] = {Type='Auto-attack damage', Goal='5000', Bonus='10% more auto-attack damage'},
		[2] = {Type=false, Goal=false, Bonus=false},
		[3] = {Type=false, Goal=false, Bonus=false},
		[4] = {Type=false, Goal=false, Bonus=false},
		[5] = {Type=false, Goal=false, Bonus=false},
	},
	['NIN'] = {
		[1] = {Type='Auto-attack damage', Goal='5000', Bonus='10% more auto-attack damage'},
		[2] = {Type=false, Goal=false, Bonus=false},
		[3] = {Type=false, Goal=false, Bonus=false},
		[4] = {Type=false, Goal=false, Bonus=false},
		[5] = {Type=false, Goal=false, Bonus=false},
	},
	['DRG'] = {
		[1] = {Type='Auto-attack damage', Goal='5000', Bonus='10% more auto-attack damage'},
		[2] = {Type=false, Goal=false, Bonus=false},
		[3] = {Type=false, Goal=false, Bonus=false},
		[4] = {Type=false, Goal=false, Bonus=false},
		[5] = {Type=false, Goal=false, Bonus=false},
	},
	['SMN'] = {
		[1] = {Type='Avatars summoned', Goal='100', Bonus='-1 avatar perpetuation cost'},
		[2] = {Type=false, Goal=false, Bonus=false},
		[3] = {Type=false, Goal=false, Bonus=false},
		[4] = {Type=false, Goal=false, Bonus=false},
		[5] = {Type=false, Goal=false, Bonus=false},
	},
	['BLU'] = {
		[1] = {Type='Physical spell damage', Goal='5000', Bonus='10% accuracy for physical blue magic spells'},
		[2] = {Type=false, Goal=false, Bonus=false},
		[3] = {Type=false, Goal=false, Bonus=false},
		[4] = {Type=false, Goal=false, Bonus=false},
		[5] = {Type=false, Goal=false, Bonus=false},
	},
	['COR'] = {
		[1] = {Type='Ranged attack damage', Goal='5000', Bonus='10% more ranged attack damage'},
		[2] = {Type=false, Goal=false, Bonus=false},
		[3] = {Type=false, Goal=false, Bonus=false},
		[4] = {Type=false, Goal=false, Bonus=false},
		[5] = {Type=false, Goal=false, Bonus=false},
	},
	['PUP'] = {
		[1] = {Type=false, Goal=false, Bonus=false},
		[2] = {Type=false, Goal=false, Bonus=false},
		[3] = {Type=false, Goal=false, Bonus=false},
		[4] = {Type=false, Goal=false, Bonus=false},
		[5] = {Type=false, Goal=false, Bonus=false},
	},
	['DNC'] = {
		[1] = {Type=false, Goal=false, Bonus=false},
		[2] = {Type=false, Goal=false, Bonus=false},
		[3] = {Type=false, Goal=false, Bonus=false},
		[4] = {Type=false, Goal=false, Bonus=false},
		[5] = {Type=false, Goal=false, Bonus=false},
	},
	['SCH'] = {
		[1] = {Type=false, Goal=false, Bonus=false},
		[2] = {Type=false, Goal=false, Bonus=false},
		[3] = {Type=false, Goal=false, Bonus=false},
		[4] = {Type=false, Goal=false, Bonus=false},
		[5] = {Type=false, Goal=false, Bonus=false},
	},
	['GEO'] = {
		[1] = {Type=false, Goal=false, Bonus=false},
		[2] = {Type=false, Goal=false, Bonus=false},
		[3] = {Type=false, Goal=false, Bonus=false},
		[4] = {Type=false, Goal=false, Bonus=false},
		[5] = {Type=false, Goal=false, Bonus=false},
	},
	['RUN'] = {
		[1] = {Type=false, Goal=false, Bonus=false},
		[2] = {Type=false, Goal=false, Bonus=false},
		[3] = {Type=false, Goal=false, Bonus=false},
		[4] = {Type=false, Goal=false, Bonus=false},
		[5] = {Type=false, Goal=false, Bonus=false},
	}
}