--Weaponskills and their stat modifiers/skillchain properties
return T{
	[1] = {en='Combo', skillchain={'Impaction'}, modifier={'STR','DEX'}},
	[2] = {en='Shoulder Tackle', skillchain={'Reverberation','Impaction'}, modifier={'VIT'}},
	[3] = {en='One Inch Punch', skillchain={'Compression'}, modifier={'VIT'}},
	[4] = {en='Backhand Blow', skillchain={'Detonation'}, modifier={'STR','DEX'}},
	[5] = {en='Raging Fists', skillchain={'Impaction'}, modifier={'STR','DEX'}},
	[6] = {en='Spinning Attack', skillchain={'Liquefaction','Impaction'}, modifier={'STR'}},
	[7] = {en='Howling Fist', skillchain={'Transfixion','Impaction'}, modifier={'VIT','STR'}},
	[8] = {en='Dragon Kick', skillchain={'Fragmentation'}, modifier={'STR','VIT'}},
	[9] = {en='Asuran Fists', skillchain={'Gravitation','Liquefaction'}, modifier={'STR','VIT'}},
	[10] = {en='Final Heaven', skillchain={'Light','Fusion'}, modifier={'VIT'}},
	[11] = {en='Ascetic\'s Fury', skillchain={'Fusion','Transfixion'}, modifier={'STR','VIT'}},
	[12] = {en='Stringing Pummel', skillchain={'Gravitation','Liquefaction'}, modifier={'STR','VIT'}},
	[13] = {en='Tornado Kick', skillchain={'Induration','Detonation','Impaction'}, modifier={'STR','VIT'}},
	[14] = {en='Victory Smite', skillchain={'Light','Fragmentation'}, modifier={'STR'}},
	[15] = {en='Shijin Spiral', skillchain={'Fusion','Reverberation'}, modifier={'DEX'}, aeonic='Light', weapon='Godhand'},
	[16] = {en='Wasp Sting', skillchain={'Scission'}, modifier={'DEX'}},
	[17] = {en='Viper Bite', skillchain={'Scission'}, modifier={'DEX'}},
	[18] = {en='Shadowstitch', skillchain={'Reverberation'}, modifier={'CHR'}},
	[19] = {en='Gust Slash', skillchain={'Detonation'}, modifier={'DEX','INT'}},
	[20] = {en='Cyclone', skillchain={'Detonation','Impaction'}, modifier={'DEX','INT'}},
	[21] = {en="Energy Steal",skillchain={}, modifier={'MND'}},
    [22] = {en="Energy Drain",skillchain={}, modifier={'MND'}},
	[23] = {en='Dancing Edge', skillchain={'Scission','Detonation'}, modifier={'DEX','CHR'}},
	[24] = {en='Shark Bite', skillchain={'Fragmentation'}, modifier={'DEX','AGI'}},
	[25] = {en='Evisceration', skillchain={'Gravitation','Transfixion'}, modifier={'DEX'}},
	[26] = {en='Mercy Stroke', skillchain={'Darkness','Gravitation'}, modifier={'STR'}},
	[27] = {en='Mandalic Stab', skillchain={'Fusion','Compression'}, modifier={'DEX'}},
	[28] = {en='Mordant Rime', skillchain={'Fragmentation','Distortion'}, modifier={'CHR','DEX'}},
	[29] = {en='Pyrrhic Kleos', skillchain={'Distortion','Scission'}, modifier={'STR','DEX'}},
	[30] = {en='Aeolian Edge', skillchain={'Scission','Detonation','Impaction'}, modifier={'DEX','INT'}},
	[31] = {en='Rudra\'s Storm', skillchain={'Darkness','Distortion'}, modifier={'DEX'}},
	[32] = {en='Fast Blade', skillchain={'Scission'}, modifier={'STR','DEX'}},
	[33] = {en='Burning Blade', skillchain={'Liquefaction'}, modifier={'STR','INT'}},
	[34] = {en='Red Lotus Blade', skillchain={'Liquefaction','Detonation'}, modifier={'STR','INT'}},
	[35] = {en='Flat Blade', skillchain={'Impaction'}, modifier={'STR'}},
	[36] = {en='Shining Blade', skillchain={'Scission'}, modifier={'STR','MND'}},
	[37] = {en='Seraph Blade', skillchain={'Scission'}, modifier={'STR','MND'}},
	[38] = {en='Circle Blade', skillchain={'Reverberation','Impaction'}, modifier={'STR'}},
	[39] = {en="Spirits Within", skillchain={}, modifier={'HP'}},
	[40] = {en='Vorpal Blade', skillchain={'Scission','Impaction'}, modifier={'STR'}},
	[41] = {en='Swift Blade', skillchain={'Gravitation'}, modifier={'STR','MND'}},
	[42] = {en='Savage Blade', skillchain={'Fragmentation','Scission'}, modifier={'STR','MND'}},
	[43] = {en='Knights of Round', skillchain={'Light','Fusion'}, modifier={'STR','MND'}},
	[44] = {en='Death Blossom', skillchain={'Fragmentation','Distortion'}, modifier={'MND','STR'}},
	[45] = {en='Atonement', skillchain={'Fusion','Reverberation'}, modifier={'Enmity'}},
	[46] = {en='Expiacion', skillchain={'Distortion','Scission'}, modifier={'STR','DEX','INT'}},
	[47] = {en="Sanguine Blade", skillchain={}, modifier={'MND','STR'}},
	[48] = {en='Hard Slash', skillchain={'Scission'}, modifier={'STR'}},
	[49] = {en='Power Slash', skillchain={'Transfixion'}, modifier={'STR','VIT'}},
	[50] = {en='Frostbite', skillchain={'Induration'}, modifier={'STR','INT'}},
	[51] = {en='Freezebite', skillchain={'Induration','Detonation'}, modifier={'STR','INT'}},
	[52] = {en='Shockwave', skillchain={'Reverberation'}, modifier={'STR','MND'}},
	[53] = {en='Crescent Moon', skillchain={'Scission'}, modifier={'STR'}},
	[54] = {en='Sickle Moon', skillchain={'Scission','Impaction'}, modifier={'STR','AGI'}},
	[55] = {en='Spinning Slash', skillchain={'Fragmentation'}, modifier={'STR','INT'}},
	[56] = {en='Ground Strike', skillchain={'Fragmentation','Distortion'}, modifier={'STR','INT'}},
	[57] = {en='Scourge', skillchain={'Light','Fusion'}, modifier={'STR','VIT'}},
	[58] = {en='Herculean Slash', skillchain={'Induration','Detonation','Impaction'}, modifier={'VIT'}},
	[59] = {en='Torcleaver', skillchain={'Light','Distortion'}, modifier={'VIT'}},
	[60] = {en='Resolution', skillchain={'Fragmentation','Scission'}, modifier={'STR'}, aeonic='Light', weapon='Lionheart'},
	[61] = {en='Dimidiation', skillchain={'Light','Fragmentation'}, modifier={'DEX'}},
	[64] = {en='Raging Axe', skillchain={'Detonation','Impaction'}, modifier={'STR'}},
	[65] = {en='Smash Axe', skillchain={'Induration','Reverberation'}, modifier={'STR'}},
	[66] = {en='Gale Axe', skillchain={'Detonation'}, modifier={'STR'}},
	[67] = {en='Avalanche Axe', skillchain={'Scission','Impaction'}, modifier={'STR'}},
	[68] = {en='Spinning Axe', skillchain={'Liquefaction','Scission','Impaction'}, modifier={'STR'}},
	[69] = {en='Rampage', skillchain={'Scission'}, modifier={'STR'}},
	[70] = {en='Calamity', skillchain={'Scission','Impaction'}, modifier={'STR','VIT'}},
	[71] = {en='Mistral Axe', skillchain={'Fusion'}, modifier={'STR'}},
	[72] = {en='Decimation', skillchain={'Fusion','Reverberation'}, modifier={'STR'}},
	[73] = {en='Onslaught', skillchain={'Darkness','Gravitation'}, modifier={'DEX'}},
	[74] = {en='Primal Rend', skillchain={'Gravitation','Reverberation'}, modifier={'CHR','DEX'}},
	[75] = {en='Bora Axe', skillchain={'Scission','Detonation'}, modifier={'DEX'}},
	[76] = {en='Cloudsplitter', skillchain={'Darkness','Fragmentation'}, modifier={'STR','MND'}},
	[77] = {en='Ruinator', skillchain={'Distortion','Detonation'}, modifier={'STR'}, aeonic='Darkness', weapon='Tri-Edge'},
	[80] = {en='Shield Break', skillchain={'Impaction'}, modifier={'STR','VIT'}},
	[81] = {en='Iron Tempest', skillchain={'Scission'}, modifier={'STR'}},
	[82] = {en='Sturmwind', skillchain={'Reverberation','Scission'}, modifier={'STR'}},
	[83] = {en='Armor Break', skillchain={'Impaction'}, modifier={'STR','VIT'}},
	[84] = {en='Keen Edge', skillchain={'Compression'}, modifier={'STR'}},
	[85] = {en='Weapon Break', skillchain={'Impaction'}, modifier={'STR','VIT'}},
	[86] = {en='Raging Rush', skillchain={'Induration','Reverberation'}, modifier={'STR'}},
	[87] = {en='Full Break', skillchain={'Distortion'}, modifier={'STR','VIT'}},
	[88] = {en='Steel Cyclone', skillchain={'Distortion','Detonation'}, modifier={'STR','VIT'}},
	[89] = {en='Metatron Torment', skillchain={'Light','Fusion'}, modifier={'STR'}},
	[90] = {en='King\'s Justice', skillchain={'Fragmentation','Scission'}, modifier={'STR'}},
	[91] = {en='Fell Cleave', skillchain={'Scission','Detonation','Impaction'}, modifier={'STR'}},
	[92] = {en='Ukko\'s Fury', skillchain={'Light','Fragmentation'}, modifier={'STR'}},
	[93] = {en='Upheaval', skillchain={'Fusion','Compression'}, modifier={'VIT'}, aeonic='Light', weapon='Chango'},
	[96] = {en='Slice', skillchain={'Scission'}, modifier={'STR'}},
	[97] = {en='Dark Harvest', skillchain={'Reverberation'}, modifier={'STR','INT'}},
	[98] = {en='Shadow of Death', skillchain={'Induration','Reverberation'}, modifier={'STR','INT'}},
	[99] = {en='Nightmare Scythe', skillchain={'Compression','Scission'}, modifier={'STR','MND'}},
	[100] = {en='Spinning Scythe', skillchain={'Reverberation','Scission'}, modifier={'STR'}},
	[101] = {en='Vorpal Scythe', skillchain={'Transfixion','Scission'}, modifier={'STR'}},
	[102] = {en='Guillotine', skillchain={'Induration'}, modifier={'MND','STR'}},
	[103] = {en='Cross Reaper', skillchain={'Distortion'}, modifier={'STR','MND'}},
	[104] = {en='Spiral Hell', skillchain={'Distortion','Scission'}, modifier={'STR','INT'}},
	[105] = {en='Catastrophe', skillchain={'Darkness','Gravitation'}, modifier={'STR','INT'}},
	[106] = {en='Insurgency', skillchain={'Fusion','Compression'}, modifier={'STR','INT'}},
	[107] = {en='Infernal Scythe', skillchain={'Compression','Reverberation'}, modifier={'INT','STR'}},
	[108] = {en='Quietus', skillchain={'Darkness','Distortion'}, modifier={'STR','MND'}},
	[109] = {en='Entropy', skillchain={'Gravitation','Reverberation'}, modifier={'INT'}, aeonic='Darkness', weapon='Anguta'},
	[112] = {en='Double Thrust', skillchain={'Transfixion'}, modifier={'STR','DEX'}},
	[113] = {en='Thunder Thrust', skillchain={'Transfixion','Impaction'}, modifier={'STR','INT'}},
	[114] = {en='Raiden Thrust', skillchain={'Transfixion','Impaction'}, modifier={'STR','INT'}},
	[115] = {en='Leg Sweep', skillchain={'Impaction'}, modifier={'STR'}},
	[116] = {en='Penta Thrust', skillchain={'Compression'}, modifier={'STR','DEX'}},
	[117] = {en='Vorpal Thrust', skillchain={'Reverberation','Transfixion'}, modifier={'STR','AGI'}},
	[118] = {en='Skewer', skillchain={'Transfixion','Impaction'}, modifier={'STR'}},
	[119] = {en='Wheeling Thrust', skillchain={'Fusion'}, modifier={'STR'}},
	[120] = {en='Impulse Drive', skillchain={'Gravitation','Induration'}, modifier={'STR'}},
	[121] = {en='Geirskogul', skillchain={'Light','Distortion'}, modifier={'DEX'}},
	[122] = {en='Drakesbane', skillchain={'Fusion','Transfixion'}, modifier={'STR'}},
	[123] = {en='Sonic Thrust', skillchain={'Transfixion','Scission'}, modifier={'STR','DEX'}},
	[124] = {en='Camlann\'s Torment', skillchain={'Light','Fragmentation'}, modifier={'STR','VIT'}},
	[125] = {en='Stardiver', skillchain={'Gravitation','Transfixion'}, modifier={'STR'}, aeonic='Darkness', weapon='Trishula'},
	[128] = {en='Blade: Rin', skillchain={'Transfixion'}, modifier={'STR','DEX'}},
	[129] = {en='Blade: Retsu', skillchain={'Scission'}, modifier={'DEX','STR'}},
	[130] = {en='Blade: Teki', skillchain={'Reverberation'}, modifier={'STR','INT'}},
	[131] = {en='Blade: To', skillchain={'Induration','Detonation'}, modifier={'STR','INT'}},
	[132] = {en='Blade: Chi', skillchain={'Transfixion','Impaction'}, modifier={'STR','INT'}},
	[133] = {en='Blade: Ei', skillchain={'Compression'}, modifier={'STR','INT'}},
	[134] = {en='Blade: Jin', skillchain={'Detonation','Impaction'}, modifier={'STR','DEX'}},
	[135] = {en='Blade: Ten', skillchain={'Gravitation'}, modifier={'STR','DEX'}},
	[136] = {en='Blade: Ku', skillchain={'Gravitation','Transfixion'}, modifier={'STR','DEX'}},
	[137] = {en='Blade: Metsu', skillchain={'Darkness','Fragmentation'}, modifier={'DEX'}},
	[138] = {en='Blade: Kamu', skillchain={'Fragmentation','Compression'}, modifier={'STR','INT'}},
	[139] = {en='Blade: Yu', skillchain={'Reverberation','Scission'}, modifier={'DEX','INT'}},
	[140] = {en='Blade: Hi', skillchain={'Darkness','Gravitation'}, modifier={'AGI'}},
	[141] = {en='Blade: Shun', skillchain={'Fusion','Impaction'}, modifier={'DEX'}, aeonic='Light', weapon='Heishi Shorinken'},
	[144] = {en='Tachi: Enpi', skillchain={'Transfixion','Scission'}, modifier={'STR'}},
	[145] = {en='Tachi: Hobaku', skillchain={'Induration'}, modifier={'STR'}},
	[146] = {en='Tachi: Goten', skillchain={'Transfixion','Impaction'}, modifier={'STR'}},
	[147] = {en='Tachi: Kagero', skillchain={'Liquefaction'}, modifier={'STR'}},
	[148] = {en='Tachi: Jinpu', skillchain={'Scission','Detonation'}, modifier={'STR'}},
	[149] = {en='Tachi: Koki', skillchain={'Reverberation','Impaction'}, modifier={'STR','MND'}},
	[150] = {en='Tachi: Yukikaze', skillchain={'Induration','Detonation'}, modifier={'STR'}},
	[151] = {en='Tachi: Gekko', skillchain={'Distortion','Reverberation'}, modifier={'STR'}},
	[152] = {en='Tachi: Kasha', skillchain={'Fusion','Compression'}, modifier={'STR'}},
	[153] = {en='Tachi: Kaiten', skillchain={'Light','Fragmentation'}, modifier={'STR'}},
	[154] = {en='Tachi: Rana', skillchain={'Gravitation','Induration'}, modifier={'STR'}},
	[155] = {en='Tachi: Ageha', skillchain={'Compression','Scission'}, modifier={'CHR','STR'}},
	[156] = {en='Tachi: Fudo', skillchain={'Light','Distortion'}, modifier={'STR'}},
	[157] = {en='Tachi: Shoha', skillchain={'Fragmentation','Compression'}, modifier={'STR'}, aeonic='Light', weapon='Dojikiri Yasutsuna'},
	[158] = {en='Tachi: Suikawari', skillchain={'Fusion'}, modifier={}},
	[160] = {en='Shining Strike', skillchain={'Impaction'}, modifier={'STR','MND'}},
	[161] = {en='Seraph Strike', skillchain={'Impaction'}, modifier={'STR','MND'}},
	[162] = {en='Brainshaker', skillchain={'Reverberation'}, modifier={'STR'}},
	[163] = {en="Starlight", skillchain={}, modifier={'Club Skill'}},
    [164] = {en="Moonlight", skillchain={}, modifier={'Club Skill'}},
	[165] = {en='Skullbreaker', skillchain={'Induration','Reverberation'}, modifier={'STR'}},
	[166] = {en='True Strike', skillchain={'Detonation','Impaction'}, modifier={'STR'}},
	[167] = {en='Judgment', skillchain={'Impaction'}, modifier={'STR','MND'}},
	[168] = {en='Hexa Strike', skillchain={'Fusion'}, modifier={'STR','MND'}},
	[169] = {en='Black Halo', skillchain={'Fragmentation','Compression'}, modifier={'MND','STR'}},
	[170] = {en='Randgrith', skillchain={'Light','Fragmentation'}, modifier={'STR','MND'}},
	[171] = {en="Mystic Boon", skillchain={}, modifier={'MND','STR'}},
	[172] = {en='Flash Nova', skillchain={'Induration','Reverberation'}, modifier={'STR','MND'}},
	[173] = {en="Dagan", skillchain={}, modifier='MaxHP','MaxMP'},
	[174] = {en='Realmrazer', skillchain={'Fusion','Impaction'}, modifier={'MND'}, aeonic='Light', weapon='Tishtrya'},
	[175] = {en='Exudation', skillchain={'Darkness','Fragmentation'}, modifier={'INT','MND'}},
	[176] = {en='Heavy Swing', skillchain={'Impaction'}, modifier={'STR'}},
	[177] = {en='Rock Crusher', skillchain={'Impaction'}, modifier={'STR','INT'}},
	[178] = {en='Earth Crusher', skillchain={'Detonation','Impaction'}, modifier={'STR','INT'}},
	[179] = {en='Starburst', skillchain={'Compression','Reverberation'}, modifier={'STR','MND'}},
	[180] = {en='Sunburst', skillchain={'Compression','Reverberation'}, modifier={'STR','MND'}},
	[181] = {en='Shell Crusher', skillchain={'Detonation'}, modifier={'STR'}},
	[182] = {en='Full Swing', skillchain={'Liquefaction','Impaction'}, modifier={'STR'}},
	[183] = {en="Spirit Taker", skillchain={}, modifier={'INT','MND'}},
	[184] = {en='Retribution', skillchain={'Gravitation','Reverberation'}, modifier={'MND','STR'}},
	[185] = {en='Gate of Tartarus', skillchain={'Darkness','Distortion'}, modifier={'INT'}},
	[186] = {en='Vidohunir', skillchain={'Fragmentation','Distortion'}, modifier={'INT'}},
	[187] = {en='Garland of Bliss', skillchain={'Fusion','Reverberation'}, modifier={'MND','STR'}},
	[188] = {en='Omniscience', skillchain={'Gravitation','Transfixion'}, modifier={'MND'}},
	[189] = {en='Cataclysm', skillchain={'Compression','Reverberation'}, modifier={'STR','INT'}},
	[190] = {en="Myrkr", skillchain={}, modifier={'MaxMP'}},
	[191] = {en='Shattersoul', skillchain={'Gravitation','Induration'}, modifier={'INT'}, aeonic='Darkness', weapon='Khatvanga'},
	[192] = {en='Flaming Arrow', skillchain={'Liquefaction','Transfixion'}, modifier={'AGI','STR'}},
	[193] = {en='Piercing Arrow', skillchain={'Reverberation','Transfixion'}, modifier={'AGI','STR'}},
	[194] = {en='Dulling Arrow', skillchain={'Liquefaction','Transfixion'}, modifier={'AGI','STR'}},
	[196] = {en='Sidewinder', skillchain={'Reverberation','Transfixion','Detonation'}, modifier={'AGI','STR'}},
	[197] = {en='Blast Arrow', skillchain={'Induration','Transfixion'}, modifier={'AGI','STR'}},
	[198] = {en='Arching Arrow', skillchain={'Fusion'}, modifier={'AGI','STR'}},
	[199] = {en='Empyreal Arrow', skillchain={'Fusion','Transfixion'}, modifier={'AGI','STR'}},
	[200] = {en='Namas Arrow', skillchain={'Light','Distortion'}, modifier={'STR','AGI'}},
	[201] = {en='Refulgent Arrow', skillchain={'Reverberation','Transfixion'}, modifier={'STR'}},
	[202] = {en='Jishnu\'s Radiance', skillchain={'Light','Fusion'}, modifier={'DEX'}},
	[203] = {en='Apex Arrow', skillchain={'Fragmentation','Transfixion'}, modifier={'AGI'}, aeonic='Light', weapon='Fail-Not'},
	[208] = {en='Hot Shot', skillchain={'Liquefaction','Transfixion'}, modifier={'AGI'}},
	[209] = {en='Split Shot', skillchain={'Reverberation','Transfixion'}, modifier={'AGI'}},
	[210] = {en='Sniper Shot', skillchain={'Liquefaction','Transfixion'}, modifier={'AGI'}},
	[212] = {en='Slug Shot', skillchain={'Reverberation','Transfixion','Detonation'}, modifier={'AGI'}},
	[213] = {en='Blast Shot', skillchain={'Induration','Transfixion'}, modifier={'AGI'}},
	[214] = {en='Heavy Shot', skillchain={'Fusion'}, modifier={'AGI'}},
	[215] = {en='Detonator', skillchain={'Fusion','Transfixion'}, modifier={'AGI'}},
	[216] = {en='Coronach', skillchain={'Darkness','Fragmentation'}, modifier={'DEX','AGI'}},
	[217] = {en='Trueflight', skillchain={'Fragmentation','Scission'}, modifier={'AGI'}},
	[218] = {en='Leaden Salute', skillchain={'Gravitation','Transfixion'}, modifier={'AGI'}},
	[219] = {en='Numbing Shot', skillchain={'Induration','Detonation','Impaction'}, modifier={'AGI'}},
	[220] = {en='Wildfire', skillchain={'Darkness','Gravitation'}, modifier={'AGI'}},
	[221] = {en='Last Stand', skillchain={'Fusion','Reverberation'}, modifier={'AGI'}, aeonic='Light', weapon='Fomalhaut'},
	[224] = {en='Exenterator', skillchain={'Fragmentation','Scission'}, modifier={'AGI'}, aeonic='Light', weapon='Aeneas'},
	[225] = {en='Chant du Cygne', skillchain={'Light','Distortion'}, modifier={'DEX'}},
	[226] = {en='Requiescat', skillchain={'Gravitation','Scission'}, modifier={'MND'}, aeonic='Darkness', weapon='Sequence'},
	[227] = {en='Knights of Rotund', skillchain={'Light'}, modifier={}},
	[228] = {en='Final Paradise', skillchain={'Light'}, modifier={}},
	[238] = {en='Uriel Blade', skillchain={'Light','Fragmentation'}, modifier={'STR','MND'}},
	[239] = {en='Glory Slash', skillchain={'Light','Fusion'}, modifier={}},
}